apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mi-certificado
  namespace: wso2-des
spec:
  secretName: secret-wso2
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
  dnsNames:
    - am.wso2.com
    - gateway.am.wso2.com
    - management.am.wso2.com
