apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-client
  namespace: wso2-des
spec:
  secretName: test-client-tls
  isCA: false
  usages:
    - client auth
  dnsNames:
  - "am.wso2.com"
  - "gateway.am.wso2.com"
  - "management.mi.wso2.com"
  - "websocket.am.wso2.com"
  - "websub.am.wso2.com"
  issuerRef:
    name: test-ca-issuer
